version: '2'

services:
  challenge:
    build: ./challenge
    expose:
      - 3780
    restart: always

  load-balancer:
    image: nginx:1.19.1-alpine
    volumes:
      - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - challenge
    expose:
      - 3780
    ports:
      - "3780:3780"
    restart: always
